server_scripts:
  startup_script: '{system.file("scheduler/startup.R", package = "restbench")}'
  batch_cluster: '{system.file("scheduler/cluster.R", package = "restbench")}'
modules:
  jobs: '{system.file("scheduler/jobs.R", package = "restbench")}'
  validate: '{system.file("scheduler/validate.R", package = "restbench")}'
options:
  debug: yes
  require_auth: no
  protocol: http
  modules_require_auth: 'jobs, validate'
  anonymous_request: no
  max_concurrent_tasks: 1
  max_concurrent_jobs: 4
  task_queue_interval: 1
  max_release_tasks_per_second: 10
  request_timeout: .inf
  task_root: '{restbench::restbench_getopt("task_root")}'
  max_nodetime: 864000
  func_newjob: restbench:::run_task
  func_validate_server: restbench::handler_validate_server

