server_scripts:
  startup_script: '{system.file("scheduler/startup.R", package = "restbatch")}'
  batch_cluster: '{system.file("scheduler/cluster.R", package = "restbatch")}'
modules:
  jobs: '{system.file("scheduler/jobs.R", package = "restbatch")}'
  validate: '{system.file("scheduler/validate.R", package = "restbatch")}'
options:
  debug: no
  protocol: http
  require_auth: yes
  anonymous_request: no
  modules_require_auth: 'jobs, validate'
  max_concurrent_tasks: 3
  max_concurrent_jobs: 8
  task_queue_interval: 1
  max_release_tasks_per_second: 10
  request_timeout: .inf
  task_root: '{restbatch::restbatch_getopt("task_root")}'
  max_nodetime: 864000
  func_newjob: restbatch:::run_task
  func_validate_server: restbatch::handler_validate_server
