modules:
  jobs: '{system.file("scheduler/jobs.R", package = "restbench")}'
  validate: '{system.file("scheduler/validate.R", package = "restbench")}'
options:
  debug: no
  require_auth: yes
  modules_require_auth: 'jobs, validate'
  anonymous_request: no
  max_concurrent_tasks: 3
  max_concurrent_jobs: 8
  task_queue_interval: 2
  request_timeout: .inf
  task_root: '{restbench::restbench_getopt("task_root")}'
  max_nodetime: 864000
  func_newjob: restbench:::run_task
  func_validate_server: restbench::handler_validate_server
